apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chip
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - cluster: https://kubernetes.default.svc                                       
    metadata:
      name: chip
    spec:
      project: "chip"
      source:
        repoURL: 'http://chartmuseum.chartmuseum.svc.cluster.local:8080'
        chart: sample
        targetRevision: 0.1.0
        helm:
          releaseName: chip
          valuesObject:
            app:
              name: chip
              image: fidelissauro/chip:v1
              namespace: chip
              version: "v2"
              capacity:
                requests: 
                  cpu: 100m
                  memory: 128Mi
                limits: 
                  cpu: 200m
                  memory: 256Mi
                autoscaling: {}
                max: 5
              rollout:
                strategy:
                    blueGreen: 
                      activeService: chip
                      previewService: chip-green
                      autoPromotionEnabled: false

                name: http-web
                port: 8080
                protocol: TCP
                targetPort: 8080
              service:
                type: ClusterIP
              istio:
                  # HTTP, HTTP2, GRPC, GRPC-WEB, MONGO, REDIS, MYSQL, TCP
                  protocol: HTTP 
                  port: 80
                host: chip.homelab.msfidelis.com.br
                virtualService:
                    enabled: true
                      attempts: 1
                DestinationRule:
                  enabled: true

              prometheus:
                port: 8080
                path: /metrics

              probes:
                livenessProbe:
                  enabled: true
                  failureThreshold: 10
                  periodSeconds: 10
                    port: 8080
                startupProbe:
                  failureThreshold: 10
                  periodSeconds: 10
                    path: /healthcheck
                    port: 8080
      destination:
        server: '{{ cluster }}'
        namespace: argocd
      syncPolicy:
        automated: {}